### ISSUE TITLE
Error when closing Anki

### ISSUE THREAD

**Issue by cjdduarte** [XavierScherschligt/RuneScape-Gamification#2]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-12-22 05:44:33

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 1117, in closeEvent
  File "aqt.main", line 512, in unloadProfileAndExit
  File "aqt.main", line 487, in unloadProfile
  File "_aqt.hooks", line 3662, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\cjddu\AppData\Roaming\Anki2\addons21\931346754\__init__.py", line 27, in save_skills
    with open("skills.json", "w") as f:
PermissionError: [Errno 13] Permission denied: 'skills.json'

**Comment by XavierScherschligt** [comment]
I am having trouble reproducing, could you download the latest version and re-test?

Thanks,
-XS

**Comment by cjdduarte** [comment]
The error continues.
What is your version of Anki?

I'm on Anki 2.1.55 QT6

**Comment by XavierScherschligt** [comment]
My current Anki/ QT version is not up-to-date: Anki Version ⁨2.1.49/Qt 5.15.1

I would expect there to be a clash with Qt  5 and 6 but I'm surprised it's happening with the save skills function during the load profile hook call. I might try to make a version for Anki 2.1.55/Qt 6 tomorrow but I believe it would also be a fix to simply downgrade to the versions I listed above. If I do end up making one, I'll comment here about it.

Thanks for the help,

-XS

**Comment by cjdduarte** [comment]
That must be why.
This new version 2.1.55 is already standard.

I await the correction, thank you.

**Comment by XavierScherschligt** [comment]
I just uploaded a version that should be compatible with Anki 2.1.55/Qt 6. Let me know your problem persists.

Best,
XS
