### ISSUE TITLE
The add-on greatly enhances the bottom bar.

### ISSUE THREAD

**Issue by cjdduarte** [XavierScherschligt/RuneScape-Gamification#3]
![image](https://user-images.githubusercontent.com/42243532/209097448-40d3800d-d310-41de-ac22-0ba82e450867.png)

![image](https://user-images.githubusercontent.com/42243532/209097705-264521e4-3f3a-4760-8c3b-b340bf01eceb.png)

**Comment by XavierScherschligt** [comment]
Should be fixed with in Version 1.0.2, let me know if not, otherwise I'll close this issue.

Best, 
-XS

**Comment by cjdduarte** [comment]
![image](https://user-images.githubusercontent.com/42243532/209237998-063a7d75-24d8-4d96-9492-2735af3c35e1.png)

**Comment by cjdduarte** [comment]
Did the add-on go to the sidebar?
I'm on Anki 2.1.55 QT6

**Comment by XavierScherschligt** [comment]
Yes, I've made it a moveable docker. If you click on the top part of the widget you can drag it to the left side or totally off of the Anki gui. Once off, you can manipulate the size of the bar. You can see the result in the screenshot I put in the README. 

Best, 

-XS
